classes: {
  uml_class: {
    shape: class
  }

  link_2: {
    style: {
      opacity: 0.5
    }
  }

  __class_utility__: {
    style: {
      opacity: 0.6
    }
  }

  __target_aggregation__: {
    target-arrowhead: {
      label: ''
      shape: diamond
    }
  }

  __source_aggregation__: {
    source-arrowhead: {
      label: ''
      shape: diamond
    }
  }
  
  __target_composition__: {
    target-arrowhead: {
      label: ''
      shape: diamond
      style: {
        filled: true
      }
    }
  }

  __source_composition__: {
    source-arrowhead: {
      label: ''
      shape: diamond
      style: {
        filled: true
      }
    }
  }
}
