version: "3.9"
services:
  cpp-algo-workshop:
    environment:
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - type: volume
        source: vscode-server-extensions
        target: /home/conan/.vscode-server/extensions
      - type: volume
        source: vscode-server-insiders-extensions
        target: /home/conan/.vscode-server-insiders/extensions
      - type: volume
        source: conan2-cache
        target: /home/conan/.conan2
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server-extensions:
    name: cpp-algo-workshop-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: cpp-algo-workshop-vscode-server-insiders-extensions
  conan2-cache:
    name: cpp-algo-workshop-conan2-cache
